<template>
<svg :class="{ heartbeat }" width="16" height="16" viewBox="0 0 54 54" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><path d="M33.651 13.44a11.14 11.14 0 0 0-8.76 4.252 6.26 6.26 0 0 0-11.213 3.83 6.4 6.4 0 0 0 .06.89 9.7 9.7 0 0 0-1.616-.145 9.09 9.09 0 0 0 0 18.174h8.128v-2.973h-8.167a6.08 6.08 0 0 1 0-12.156 7 7 0 0 1 1.087.1l4.107.738-.6-4.153a2.3 2.3 0 0 1 0-.455 3.26 3.26 0 0 1 5.84-2.004l2.354 3 2.386-3a8.1 8.1 0 0 1 6.394-3.098l-.04.072a8.1 8.1 0 0 1 8.148 7.937l.06 2.314 2.234.54a5.15 5.15 0 0 1 3.935 4.997v.171a5.17 5.17 0 0 1-5.148 4.997h-9.09v2.973h9.09A8.18 8.18 0 0 0 51 32.32a8.17 8.17 0 0 0-6.242-7.937A11.16 11.16 0 0 0 33.612 13.5z"/><g transform="translate(13.498 30.375)scale(1.6875)" shape-rendering="geometricPrecision"><circle cx="8.001" cy="4" r="1"/><circle cx="8.001" cy="8" r="1"/><circle cx="8.001" cy="11.992" r="1"/></g><path d="M20.25 33.75h3.417L27 30.417l3.333 3.333h3.417L27 27Z"/></svg>
</template>

<script setup>
defineProps({
    heartbeat: {
        type: Boolean,
        default: false,
    },
});
</script>

<style scoped>
.heartbeat {
    animation: heartbeat 1.5s ease-in-out 2s infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-9-23 10:43:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@keyframes heartbeat {
  from {
    transform: scale(1);
    transform-origin: center center;
    animation-timing-function: ease-out;
  }
  10% {
    transform: scale(0.91);
    animation-timing-function: ease-in;
  }
  17% {
    transform: scale(0.98);
    animation-timing-function: ease-out;
  }
  33% {
    transform: scale(0.87);
    animation-timing-function: ease-in;
  }
  45% {
    transform: scale(1);
    animation-timing-function: ease-out;
  }
}
</style>